#!/bin/sh

#valido que este corriendo solo una vez
if [ -e ./.cont_temp ]; then
    echo "No se puede iniciar, DetectaW5 ya esta corriendo"
else
    touch ./.cont_temp
    echo "Iniciando comando DetectaW5..."
    
    $BINDIR/DetectaW5.sh & 

    echo "Ok"
fi


