#!/bin/bash
if [ -e "${TEMPDIR}/.cont_temp" ]; then

    rm "${TEMPDIR}/.cont_temp"

    echo "Deteniendo comando DetectaW5..."
	
	pkill "DetectaW5.sh"
	PIDDETECTA=$(pgrep DetectaW5.sh)
	if [ -z $PIDDETECTA ] ; then
		echo "DetectaW5 se ha detenido correctamente"
	else
		echo "Error al intentar detener a DetectaW5"
	fi

else
    echo "El comando DetectaW5 ya se encuentra detenido"
fi
